name: fitlife
description: "A Flutter project for FitLife app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI & State
  cupertino_icons: ^1.0.5
  get: ^4.6.6

  # Charts
  fl_chart: ^1.1.1

  # Local storage
  shared_preferences: ^2.3.2

  # Video (ONLY one stack)
  video_player: ^2.10.1
  chewie: ^1.13.0

  # Firebase (MINIMAL)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   # - assets/videos/

  fonts:
    - family: Poppins
      fonts:
       # - asset: assets/fonts/Poppins-Regular.ttf
       #- asset: assets/fonts/Poppins-Medium.ttf
       # - asset: assets/fonts/Poppins-SemiBold.ttf
       # - asset: assets/fonts/Poppins-Bold.ttf
