// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VdGvB4TEvPPvjePRI-HWtRXJcs2RjKs',
    appId: '1:820642764441:web:6a944e5ae17ab997ddca08',
    messagingSenderId: '820642764441',
    projectId: 'fitlife-3668f',
    authDomain: 'fitlife-3668f.firebaseapp.com',
    storageBucket: 'fitlife-3668f.appspot.com',
    measurementId: 'G-1F29HW9CG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXtqsXnc3c9NPOAdAntTT0Dds2ycADcQ',
    appId: '1:820642764441:android:e407abe914a22b03ddca08',
    messagingSenderId: '820642764441',
    projectId: 'fitlife-3668f',
    storageBucket: 'fitlife-3668f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavGxLlXTzDCfzn5UxIc5mPu6CZG7hcuM',
    appId: '1:820642764441:ios:19542e7beb7deeeeddca08',
    messagingSenderId: '820642764441',
    projectId: 'fitlife-3668f',
    storageBucket: 'fitlife-3668f.appspot.com',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDavGxLlXTzDCfzn5UxIc5mPu6CZG7hcuM',
    appId: '1:820642764441:ios:19542e7beb7deeeeddca08',
    messagingSenderId: '820642764441',
    projectId: 'fitlife-3668f',
    storageBucket: 'fitlife-3668f.appspot.com',
    iosBundleId: 'com.example.fitlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_VdGvB4TEvPPvjePRI-HWtRXJcs2RjKs',
    appId: '1:820642764441:web:b68dde51f6210199ddca08',
    messagingSenderId: '820642764441',
    projectId: 'fitlife-3668f',
    authDomain: 'fitlife-3668f.firebaseapp.com',
    storageBucket: 'fitlife-3668f.appspot.com',
    measurementId: 'G-LEV0CCJH40',
  );
}
